[package]
name = "pineapple"
version = "0.1.0"
authors = ["phantom <623601391@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
